### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### GitHub Corrected URLs 
Was | Now 
--- | --- 
https://github.com/modeset/guard-teabag | https://github.com/modeset/guard-teaspoon 
https://github.com/modeset/teabag | https://github.com/modeset/teaspoon 
https://github.com/socialreferral/guard-process | https://github.com/guard/guard-process 

### HTTPS Corrected URLs 
Was | Now 
--- | --- 
http://travis-ci.org/ | https://travis-ci.org/ 
http://travis-ci.org/guard/guard-jasmine | https://travis-ci.org/guard/guard-jasmine 
http://twitter.com/#!/AriyaHidayat | https://twitter.com/#!/AriyaHidayat 
http://twitter.com/#!/bradgonesurfing | https://twitter.com/#!/bradgonesurfing 
http://twitter.com/#!/jashkenas | https://twitter.com/#!/jashkenas 

### Other Corrected URLs 
Was | Now 
--- | --- 
http://gembundler.com/ | http://bundler.io 
http://jashkenas.github.com/coffee-script/ | http://coffeescript.org/
http://mxcl.github.com/homebrew/ | http://brew.sh/
http://rubydoc.info/github/guard/guard-jasmine/master/frames | http://www.rubydoc.info/github/guard/guard-jasmine/master/frames 
http://rudylattae.github.com/jasmine-species/ | http://rudylattae.github.io/jasmine-species/

### CODE REVIEW

**Comment by nathanstitt** [comment]
Thanks, but some of the suggested links are incorrect.  For instance both coffee script urls are dead, and should just be coffeescript.org, and home-brew should be just brew.sh.

If you'd like to verify and update the links, I'd be happy to accept the PR.  Otherwise I'll go through and check and update manually this weekend.

**Comment by ReadmeCritic** [comment]
@nathanstitt updated

**Comment by nathanstitt** [comment]
Thanks very much!

**Comment by ReadmeCritic** [comment]
:smile:

**Pull request merged**
